springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Api Gateway
        url: /v3/api-docs
      - name: User Service
        url: http://172.17.0.1:8080/v3/api-docs
      - name: Transaction Service
        url: http://172.17.0.1:8081/v3/api-docs
      - name: Payment Service
        url: http://172.17.0.1:8082/v3/api-docs

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: api-gateway
    distribution:
      percentiles-histogram:
        http.server.requests: true   # active les histogrammes


  endpoint:
    health:
      show-details: always
server:
  port: 5050
  error:
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b"
      directory: logs
      prefix: access_log
      suffix: .txt


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      server:
        webmvc:
          routes:
            - id: users-service
              uri: http://users-service:8080
              predicates:
                - Path=/users/**
                - Method=GET,POST,PUT,DELETE
            - id: transaction-service
              uri: http://transactions-service:8081
              predicates:
                - Path=/orders/**
                - Method=GET,POST,PUT,DELETE
            - id: payment-service
              uri: http://payments-service:8082
              predicates:
                - Path=/approvisionnements/**
                - Method=GET,POST,PUT,DELETE



